### ISSUE TITLE
Exception when suscribe to /imu_mag

### ISSUE THREAD

**Issue by GilenTell** [ROS-Aceinna/ros_openimu#1]
Hi,
I think I am the first Beta-tester of the openimu Ros driver.
I have corrected some bugs that I have found when launching the driver.
In setup.py line 4: packages=['openimu'], -> packages=['ros_openimu'],
In openimu_driver.py line 10: from aceinna.tools import OpenIMU -> from ros_openimu.aceinna.tools import OpenIMU
In internal_combine_app_parse_rule.py line 5: start_str: ''-> name = ''
In internal_combine_app_parse_rule.py line 6: start_str: '' -> start_str = ''

I notice that the driver runs with python 3, and it is reporting an error with python 2.7. I have changed the first line of openimu_driver.py: #!/usr/bin/env python -> #!/usr/bin/env python3

I am running the driver by this command and it founds my connected openIMU300ZI.
`rosrun ros_openimu openimu_driver.py`

I suscribe with rqt to /imu_acc_ar topic, and all it's right and I can monitor the angular_velocity and linear_acceleration (not orientation).

But when I suscribe to /imu_mag, an exception is ocurred and the driver stop. Here is the console debug info:

```
load package from local
start to find device
2021-03-23 11:02:54,204 - /home/naitec/catkin_ws/src/ros_openimu/src/aceinna/framework/communicator.py[line:285] - INFO: try to use last connected port /dev/ttyUSB0 115200
2021-03-23 11:02:54,209 - /home/naitec/catkin_ws/src/ros_openimu/src/aceinna/devices/device_manager.py[line:153] - DEBUG: Checking if is OpenRTK/OpenIMU device...
2021-03-23 11:02:54,273 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:115] - DEBUG: requestTopic('/rosout', '/rosout', [['TCPROS']])
2021-03-23 11:02:54,275 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:545] - DEBUG: requestTopic[/rosout]: choosing protocol TCPROS
2021-03-23 11:02:54,276 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:147] - DEBUG: requestTopic('/rosout', '/rosout', [['TCPROS']]) returns (1, 'ready on naitec-nvidiatx2:41003', ['TCPROS', 'naitec-nvidiatx2', 41003])
2021-03-23 11:02:54,381 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py[line:640] - DEBUG: [/rosout]: writing header
2021-03-23 11:02:54,385 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py[line:140] - INFO: topic[/rosout] adding connection to [/rosout], count 0
2021-03-23 11:02:54,477 - /home/naitec/catkin_ws/src/ros_openimu/src/aceinna/devices/device_manager.py[line:164] - DEBUG: Device: OpenIMU300ZI 5020-3885-01 1.0.30 SN:1908400260
2021-03-23 11:02:54,477 - /home/naitec/catkin_ws/src/ros_openimu/src/aceinna/devices/device_manager.py[line:166] - DEBUG: Firmware: OpenIMU Framework 1.0.0
Connected OpenIMU
Device: OpenIMU300ZI 5020-3885-01 1.0.30 SN:1908400260
Firmware: OpenIMU Framework 1.0.0
2021-03-23 11:02:54,478 - /home/naitec/catkin_ws/src/ros_openimu/src/aceinna/devices/device_manager.py[line:194] - INFO: Connected OpenIMU300ZI 5020-3885-01 1.0.30 SN:1908400260, OpenIMU Framework 1.0.0
[INFO] [1616493774.479696]: OpenIMU driver initialized.
2021-03-23 11:02:54,479 - /home/naitec/catkin_ws/src/ros_openimu/scripts/openimu_driver.py[line:51] - INFO: OpenIMU driver initialized.
2021-03-23 11:03:02,469 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:115] - DEBUG: requestTopic('/rqt_gui_py_node_8699', '/imu_acc_ar', [['TCPROS']])
2021-03-23 11:03:02,477 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:545] - DEBUG: requestTopic[/imu_acc_ar]: choosing protocol TCPROS
2021-03-23 11:03:02,478 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:147] - DEBUG: requestTopic('/rqt_gui_py_node_8699', '/imu_acc_ar', [['TCPROS']]) returns (1, 'ready on naitec-nvidiatx2:41003', ['TCPROS', 'naitec-nvidiatx2', 41003])
2021-03-23 11:03:02,485 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py[line:640] - DEBUG: [/imu_acc_ar]: writing header
2021-03-23 11:03:02,488 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py[line:140] - INFO: topic[/imu_acc_ar] adding connection to [/rqt_gui_py_node_8699], count 0
2021-03-23 11:08:37,525 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py[line:140] - INFO: topic[/imu_acc_ar] removing connection to /rqt_gui_py_node_8699
2021-03-23 11:08:39,029 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:115] - DEBUG: requestTopic('/rqt_gui_py_node_8699', '/imu_mag', [['TCPROS']])
2021-03-23 11:08:39,030 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:545] - DEBUG: requestTopic[/imu_mag]: choosing protocol TCPROS
2021-03-23 11:08:39,031 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:147] - DEBUG: requestTopic('/rqt_gui_py_node_8699', '/imu_mag', [['TCPROS']]) returns (1, 'ready on naitec-nvidiatx2:41003', ['TCPROS', 'naitec-nvidiatx2', 41003])
2021-03-23 11:08:39,037 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py[line:640] - DEBUG: [/imu_mag]: writing header
2021-03-23 11:08:39,039 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py[line:140] - INFO: topic[/imu_mag] adding connection to [/rqt_gui_py_node_8699], count 0
2021-03-23 11:08:39,079 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py[line:885] - ERROR: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/msg/_MagneticField.py", line 118, in serialize
    buff.write(_get_struct_9d().pack(*self.magnetic_field_covariance))
TypeError: pack() argument after * must be an iterable, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/msg/_MagneticField.py", line 120, in serialize
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 362, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 281, in check_type
    raise SerializationError('field %s must be a list or tuple type' % field_name)
genpy.message.SerializationError: field magnetic_field_covariance must be a list or tuple type

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/msg/_MagneticField.py", line 118, in serialize
    buff.write(_get_struct_9d().pack(*self.magnetic_field_covariance))
TypeError: pack() argument after * must be an iterable, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/msg/_MagneticField.py", line 120, in serialize
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 362, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 281, in check_type
    raise SerializationError('field %s must be a list or tuple type' % field_name)
genpy.message.SerializationError: field magnetic_field_covariance must be a list or tuple type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naitec/catkin_ws/src/ros_openimu/scripts/openimu_driver.py", line 79, in <module>
    pub_mag.publish(mag_msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field magnetic_field_covariance must be a list or tuple type
2021-03-23 11:08:39,131 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py[line:556] - INFO: signal_shutdown [atexit]
2021-03-23 11:08:39,131 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/registration.py[line:336] - DEBUG: registration cleanup starting
2021-03-23 11:08:39,132 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/registration.py[line:368] - DEBUG: unregisterPublisher [/rosout]
2021-03-23 11:08:39,132 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/registration.py[line:368] - DEBUG: unregisterPublisher [/imu_acc_ar]
2021-03-23 11:08:39,133 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/registration.py[line:368] - DEBUG: unregisterPublisher [/imu_mag]
2021-03-23 11:08:39,133 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/registration.py[line:373] - DEBUG: unregisterService [/openimu_driver/get_loggers]
2021-03-23 11:08:39,133 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/registration.py[line:373] - DEBUG: unregisterService [/openimu_driver/set_logger_level]
2021-03-23 11:08:39,139 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/registration.py[line:385] - DEBUG: registration cleanup: master calls complete
2021-03-23 11:08:39,139 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py[line:140] - INFO: topic[/rosout] removing connection to /rosout
2021-03-23 11:08:39,140 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py[line:140] - INFO: topic[/imu_mag] removing connection to /rqt_gui_py_node_8699
2021-03-23 11:08:39,141 - /opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/masterslave.py[line:342] - INFO: atexit
```

Thank you,
Guillermo

**Comment by ROS-Aceinna** [comment]
Thank you for the feedback GilenTell. We have updated the repo to hopefully eliminate the issues.

**Comment by GilenTell** [comment]
Hi,
I have tested the new version, there isn't any python execution error and it seems that the magnetic topic is published right.
But Iike I have reported with accelerometer in issue https://github.com/ROS-Aceinna/ros_openimu/issues/3 , the higher frequency of the magnetic topic is 24Hz too.
Thank you and regards,
Guillermo
